// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAll():Promise<void>;

export function GenerateModelsEmbeddings():Promise<void>;

export function GenerateStagesEmbeddings():Promise<void>;
