// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAll() {
  return window['go']['handlers']['Embeddings']['GenerateAll']();
}

export function GenerateModelsEmbeddings() {
  return window['go']['handlers']['Embeddings']['GenerateModelsEmbeddings']();
}

export function GenerateStagesEmbeddings() {
  return window['go']['handlers']['Embeddings']['GenerateStagesEmbeddings']();
}
