// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageAsBase64(arg1) {
  return window['go']['handlers']['Images']['GetImageAsBase64'](arg1);
}

export function GetVideoAsBase64(arg1) {
  return window['go']['handlers']['Images']['GetVideoAsBase64'](arg1);
}
