// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageAsBase64(arg1:string):Promise<string>;

export function GetVideoAsBase64(arg1:string):Promise<string>;
