// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetAllModels():Promise<Array<entities.Model>>;

export function GetModels(arg1:number,arg2:number):Promise<entities.Pagination_MMDContent_internal_entities_Model_>;

export function RefreshModelsData():Promise<void>;

export function SearchModels(arg1:string,arg2:number):Promise<Array<entities.Model>>;
