// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllModels() {
  return window['go']['handlers']['Models']['GetAllModels']();
}

export function GetModels(arg1, arg2) {
  return window['go']['handlers']['Models']['GetModels'](arg1, arg2);
}

export function RefreshModelsData() {
  return window['go']['handlers']['Models']['RefreshModelsData']();
}

export function SearchModels(arg1, arg2) {
  return window['go']['handlers']['Models']['SearchModels'](arg1, arg2);
}
