// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllMotions() {
  return window['go']['handlers']['Motions']['GetAllMotions']();
}

export function GetMotions(arg1, arg2) {
  return window['go']['handlers']['Motions']['GetMotions'](arg1, arg2);
}

export function RefreshMotionsData() {
  return window['go']['handlers']['Motions']['RefreshMotionsData']();
}

export function SearchMotions(arg1, arg2) {
  return window['go']['handlers']['Motions']['SearchMotions'](arg1, arg2);
}
