// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetAllMotions():Promise<Array<entities.Motion>>;

export function GetMotions(arg1:number,arg2:number):Promise<entities.Pagination_MMDContent_internal_entities_Motion_>;

export function RefreshMotionsData():Promise<void>;

export function SearchMotions(arg1:string,arg2:number):Promise<Array<entities.Motion>>;
