// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllStages() {
  return window['go']['handlers']['Stages']['GetAllStages']();
}

export function GetStages(arg1, arg2) {
  return window['go']['handlers']['Stages']['GetStages'](arg1, arg2);
}

export function RefreshStagesData() {
  return window['go']['handlers']['Stages']['RefreshStagesData']();
}

export function SearchStages(arg1, arg2) {
  return window['go']['handlers']['Stages']['SearchStages'](arg1, arg2);
}
