// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetAllStages():Promise<Array<entities.Stage>>;

export function GetStages(arg1:number,arg2:number):Promise<entities.Pagination_MMDContent_internal_entities_Stage_>;

export function RefreshStagesData():Promise<void>;

export function SearchStages(arg1:string,arg2:number):Promise<Array<entities.Stage>>;
