// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetImageAsBase64(arg1) {
  return window['go']['main']['App']['GetImageAsBase64'](arg1);
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshModelsData() {
  return window['go']['main']['App']['RefreshModelsData']();
}
