// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllModels():Promise<Array<main.Model>>;

export function GetImageAsBase64(arg1:string):Promise<string>;

export function GetModels(arg1:number,arg2:number):Promise<main.PaginatedModels>;

export function Quit():Promise<void>;

export function RefreshModelsData():Promise<void>;
