// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateEmbeddingsForAll() {
  return window['go']['main']['App']['GenerateEmbeddingsForAll']();
}

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetAllStages() {
  return window['go']['main']['App']['GetAllStages']();
}

export function GetImageAsBase64(arg1) {
  return window['go']['main']['App']['GetImageAsBase64'](arg1);
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetStages(arg1, arg2) {
  return window['go']['main']['App']['GetStages'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshModelsData() {
  return window['go']['main']['App']['RefreshModelsData']();
}

export function RefreshStagesData() {
  return window['go']['main']['App']['RefreshStagesData']();
}

export function SearchModels(arg1, arg2) {
  return window['go']['main']['App']['SearchModels'](arg1, arg2);
}

export function SearchStages(arg1, arg2) {
  return window['go']['main']['App']['SearchStages'](arg1, arg2);
}
